# Generated by Django 5.0.4 on 2024-05-14 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('system_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('system_name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Информационные системы',
                'verbose_name_plural': 'Информационные системы',
                'db_table': 'auth_systems',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Идентификатор')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('birthday', models.DateField(default='2001-01-01', verbose_name='Дата рождения')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('gender', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не указан', 'Не указан')], default='Не указан', max_length=16, verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'auth_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('user_uuid', models.UUIDField(db_column='user_system_uuid', db_index=True, verbose_name='Идентификатор пользователя в системе')),
                ('user_id', models.ForeignKey(db_column='user_id', default=uuid.UUID('18e97b62-e4d5-4e80-9666-54572650b0d1'), on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль')),
                ('user_system', models.ForeignKey(db_column='system_uuid', on_delete=django.db.models.deletion.CASCADE, to='users.systems', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Интеграционные данные профилей',
                'verbose_name_plural': 'Интеграционные данные профилей',
                'db_table': 'auth_user_systems',
            },
        ),
        migrations.AddConstraint(
            model_name='usersystem',
            constraint=models.UniqueConstraint(fields=('user_id', 'user_system'), name='users_usersystem_unique'),
        ),
    ]
