# Generated by Django 5.0.4 on 2024-05-15 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=uuid.UUID('d7d1cbfe-0f3f-48c0-a7bb-6427d0440259'), on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль'),
        ),
    ]
