# Generated by Django 5.0.6 on 2024-05-16 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersystem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=uuid.UUID('db6443df-824f-48c3-abbc-0113161f88c1'), on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль'),
        ),
    ]
