# Generated by Django 5.0.4 on 2024-05-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата записи'),
        ),
    ]
