# Generated by Django 5.0.6 on 2024-05-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0002_alter_orderhistory_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderuserrole',
            name='department',
        ),
        migrations.AddField(
            model_name='orderuserprofile',
            name='department',
            field=models.ForeignKey(db_column='department', default='c9940d97-0bdc-4d89-8808-7a1c57572816', on_delete=django.db.models.deletion.CASCADE, to='opened_orders.orderuserdepartment'),
        ),
    ]
