# Generated by Django 5.0.6 on 2024-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0003_remove_orderuserrole_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedorder',
            name='number',
            field=models.IntegerField(auto_created=True, db_column='number', default=1, editable=False, verbose_name='Номер заявки'),
            preserve_default=False,
        ),
    ]
