# Generated by Django 5.0.6 on 2024-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_city_code'),
        ('opened_orders', '0004_openedorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedorder',
            name='number',
            field=models.IntegerField(db_column='number', default=0, editable=False, verbose_name='Номер заявки'),
        ),
        migrations.AddIndex(
            model_name='openedorder',
            index=models.Index(fields=['number'], name='number'),
        ),
    ]
