# Generated by Django 5.0.6 on 2024-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0006_alter_openedorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedorder',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Отдел', 'Отдел'), ('Компания', 'Компания')], default='Отдел', max_length=16, verbose_name='Пол'),
        ),
    ]
