# Generated by Django 5.0.6 on 2024-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0007_openedorder_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedorder',
            name='number',
            field=models.BigIntegerField(auto_created=True, db_column='number', editable=False, verbose_name='Номер заявки'),
        ),
    ]
