# Generated by Django 5.0.6 on 2024-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0009_remove_orderuserdepartment_chief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuserdepartment',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование'),
        ),
    ]
