# Generated by Django 5.0.6 on 2024-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opened_orders', '0011_alter_openedorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedorder',
            name='number',
            field=models.BigIntegerField(db_column='number', default=0, verbose_name='Номер заявки'),
        ),
    ]
