# Generated by Django 5.0.6 on 2024-07-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_telegrambotusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBotUsers',
        ),
    ]
